stages:
  data_ingestion:
    cmd: PYTHONPATH=. python data/data_ingestion.py
    deps:
    - data/data_ingestion.py
    params:
    - data_ingestion.no_rows
    outs:
    - processedData/raw/full_dataset.csv

  data_preprocessing:
    cmd: PYTHONPATH=. python data/data_preprocessing.py
    deps:
    - data/data_preprocessing.py
    - processedData/raw/full_dataset.csv
    params:
    - data_preprocessing.test_size
    outs:
    - processedData/preprocessed/
    - model/pipeline/
    - model/pipeline/
    - Metadata/

  train_vae:
    cmd: PYTHONPATH=. python model/train_vae.py
    deps:
    - processedData/preprocessed/trainset_VAE.npy
    - processedData/preprocessed/testset_VAE.npy
    - processedData/preprocessed/testset_label.npy
    - model/VAE.py
    - model/train_vae.py
    params:
    - train_vae.batch_size
    - train_vae.epoch
    - train_vae.beta
    - train_vae.z_dim
    - train_vae.lr
    - train_vae.warmup_epochs
    outs:
    - model/best_vae.pt