stages:
  data_ingestion:
    cmd: PYTHONPATH=. python data/data_ingestion.py
    deps:
    - data/data_ingestion.py
    params:
    - data_ingestion.no_rows
    outs:
    - processedData/raw/full_dataset.csv

  data_preprocessing:
    cmd: PYTHONPATH=. python data/data_preprocessing.py
    deps:
    - data/data_preprocessing.py
    - processedData/raw/full_dataset.csv
    params:
    - data_preprocessing.test_size
    outs:
    - processedData/preprocessed/
    - model/pipeline/
    - model/pipeline/
    - Metadata/

  train_vae:
    cmd: PYTHONPATH=. python model/train_vae.py
    deps:
    - processedData/preprocessed/trainset_VAE.npy
    - processedData/preprocessed/testset_VAE.npy
    - processedData/preprocessed/testset_label.npy
    - model/VAE.py
    - model/train_vae.py
    params:
    - train_vae.batch_size
    - train_vae.epoch
    - train_vae.beta
    - train_vae.z_dim
    - train_vae.lr
    - train_vae.warmup_epochs
    - train_vae.seed
    outs:
    - model/best_vae.pt

  train_iso:
    cmd: PYTHONPATH=. python model/train_iso.py
    deps:
    - processedData/preprocessed/trainset_Iso.npy
    - model/train_iso.py
    params:
    - train_iso.n_estimator
    - train_iso.contamination
    - train_iso.max_feature
    - train_iso.random_state
    outs:
    - model/iso_forest.pkl

  model_evaluation:
    cmd: PYTHONPATH=. python model/model_evaluation.py
    deps:
    - processedData/preprocessed/testset_VAE.npy
    - processedData/preprocessed/testset_label.npy
    - model/VAE.py
    - processedData/preprocessed/testset_Iso.npy
    - model/model_evaluation.py
    - model/best_vae.pt
    - model/iso_forest.pkl
    - model/pipeline/transform_rule_VAE.pkl
    - model/pipeline/transform_rule_Iso.pkl
    params:
    - train_vae.batch_size
    - train_vae.z_dim
    - train_vae.seed
    - model_evaluation.vae_w
    - model_evaluation.iso_w
    outs:
    - Metrics/Plots

  model_registry:
    cmd: PYTHONPATH=. python model/model_registry.py
    deps:
    - Metadata/experiment_info.json
    - model/model_registry.py